def addNames(Names) -> set:
    Names.add("Canó")
    Names.add("Díaz")
    Names.add("Jiménez")
    Names.add("Mariñez")
    Names.add("Márquez")
    Names.add("Mondesí")
    Names.add("Rodríguez")
    Names.add("Tatís")

    Names.add("Hwan Bae")
    Names.add("Ruíz")
    Names.add("Álvarez")
    Names.add("Pérez")
    Names.add("Colás")
    
    Names.add("García")
    Names.add("Germán")
    Names.add("Gómez")
    Names.add("Loáisiga")
    Names.add("Rodón")
    Names.add("Rodón")
    Names.add("Hernández")
    Names.add("Urías")
    Names.add("Patiño")
    Names.add("Mejía")
    Names.add("Bruján")
    Names.add("Ramírez")
    Names.add("Giménez")
    Names.add("López")
    Names.add("Pagán")
    Names.add("Vázquez")
    Names.add("Báez")
    Names.add("Colás")
    Names.add("González")
    Names.add("León")
    Names.add("Acuñas")
    Names.add("Acuña")
    Names.add("Dubón")
    Names.add("Peña")
    Names.add("Estévez")
    Names.add("Barría")
    Names.add("Muñoz")
    Names.add("Suárez")
    Names.add("Piña")
    Names.add("Frías")
    Names.add("Ureña")
    Names.add("Alcántara")
    Names.add("Narváez")
    Names.add("Encarnación")
    Names.add("Domínguez")
    Names.add("Sánchez")
    Names.add("Marchán")

    return Names
